python3.5: workaround pytest failing with "pathlib2" import error
```
$ pipenv run pytest --cov=ical2vdir --cov-report=term-missing --cov-fail-under=100
Traceback (most recent call last):
[...]
  File "/home/runner/.local/share/virtualenvs/ical2vdir-io57R1Nw/lib/python3.5/site-packages/_pytest/assertion/rewrite.py", line 30, in <module>
    from _pytest.pathlib import fnmatch_ex
  File "/home/runner/.local/share/virtualenvs/ical2vdir-io57R1Nw/lib/python3.5/site-packages/_pytest/pathlib.py", line 26, in <module>
    from pathlib2 import Path, PurePath
ImportError: No module named 'pathlib2'
```
https://github.com/fphammerle/ical2vdir/pull/10/checks?check_run_id=783280938#step:8:17